apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: heimdall
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      hostNetwork: true
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 31897
        env:
        - name: ME_CONFIG_MONGODB_URL
          value: "mongodb://localhost:27017/"
        - name: ME_CONFIG_BASICAUTH_USERNAME
          value: "admin"
        - name: ME_CONFIG_BASICAUTH_PASSWORD
          value: "pass"
        - name: ME_CONFIG_SITE_BASEURL
          value: "/"
        - name: PORT
          value: "31897"
        - name: VCAP_APP_PORT
          value: "31897"
