apiVersion: v1
kind: Service
metadata:
  name: glances
  namespace: heimdall
spec:
  type: LoadBalancer
  ports:
  - port: 31892
    targetPort: 31892
    nodePort: 31892
  selector:
    app: glances
