apiVersion: v1
kind: Service
metadata:
  name: node-exporter
  namespace: heimdall
spec:
  type: LoadBalancer
  ports:
  - port: 31893
    targetPort: 31893
    nodePort: 31893
  selector:
    app: node-exporter
