apiVersion: v1
kind: Service
metadata:
  name: storage-bucket
  namespace: heimdall
spec:
  type: LoadBalancer
  ports:
  - port: 31896
    targetPort: 31896
    nodePort: 31896
  selector:
    app: storage-bucket
