apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heimdall-config-pvc
  namespace: heimdall
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: microk8s-hostpath
